### ISSUE TITLE
review api 수정 요청

### ISSUE THREAD

**Issue by tnals0924** [git-hubsalt/omoib-backend#14]
/review/update  api가 디자인 수정 이전 버전인 것 같습니다.

기존에는 리뷰를 이모티콘이나 날씨 적합도 등으로 작성했지만, 현재는 줄 글 형태로 리뷰를 받고 있습니다.

피그마 확인 후, 변경 부탁드립니다.

**Comment by sinam7** [comment]
history 조회 시 review 누락

**Comment by sinam7** [comment]
> 기존에는 리뷰를 이모티콘이나 날씨 적합도 등으로 작성했지만, 현재는 줄 글 형태로 리뷰를 받고 있습니다.
https://github.com/git-hubsalt/omoib-backend/blob/93a4a0bfde315ce02ec0b8aa69e04e38d83c04fe/src/main/java/com/githubsalt/omoib/review/Review.java#L16-L32

기존에도 해당 값을 `String`으로 받아 처리하고 있었습니다. 
다만 직전 '히스토리 조회 시 리뷰 누락'을 처리하는 과정에서 해당 정보를 가져오기 쉽도록 변경해 두었습니다.

https://github.com/git-hubsalt/omoib-backend/blob/751de50ca845463500106471099211f4d582fa4a/src/main/java/com/githubsalt/omoib/review/dto/ReviewResponseBriefDTO.java#L3-L8

이 부분의 필드를 사용하면 될 것이라고 이해해 위 내용대로 개발해 둔 상태입니다. 혹시 다른 내용이 있을까요?

**Comment by sinam7** [comment]
추가: 필드 Json 직렬화 결과는 대략 이런 모양입니다.

- HistoryReviewDTO
  - History
    - id, type, date, user, ...
  - ReviewResponseBriefDTO
     - **temperatureSuitability**
     - **preference**

**Comment by sinam7** [comment]
@tnals0924 리마인더

**Comment by tnals0924** [comment]
확인이 늦어져서 죄송합니다! 현재 리뷰 ui가 아래와 같이 하나의 텍스트 박스에서 줄글 형태로 받고 있어서 temperatureSuitability와 preference로 따로 나눌 필요가 없어졌다는 말씀을 드렸던 겁니다.

@sinam7 

구체적인 디자인은 피그마 참조해주시면 감사하겠습니다.

<img width="703" alt="스크린샷 2024-11-07 오후 12 39 16" src="https://github.com/user-attachments/assets/c733ec67-347b-4c4c-935c-51657893fe76">

**Comment by sinam7** [comment]
Review Entity 수정
* temperature, preference 필드 삭제
* text: String 필드 생성
    * 이에 맞추어 모든 관련 소스코드 구조 변경 필요 (Entity, Service, DTOs)

예상 response json
> HistoryReviewDTO
> * History
>     * id, type, date, user, ...
> * reviewText: String
