### ISSUE TITLE
옷 타입 수정

### ISSUE THREAD

**Issue by sinam7** [git-hubsalt/omoib-backend#6]
https://github.com/git-hubsalt/omoib-backend/blob/4d7414ba01fd9029e10ebc0b96b1fc5788ee808f/src/main/java/com/githubsalt/omoib/clothes/enums/ClothesType.java#L5-L10

https://github.com/git-hubsalt/omoib-backend/blob/4d7414ba01fd9029e10ebc0b96b1fc5788ee808f/src/main/java/com/githubsalt/omoib/bodymasking/enums/MaskingType.java#L5-L10

현재 마스킹 구현이 아래처럼 5개 타입(상의,하의,바지,치마,한벌옷)으로 되어 있는데, 실제 옷 타입 label이 다른 상태.
Sync가 필요해 보이는데, 의도된 사항인지 확인 필요
(둘 중 무엇이 Outdated?)

**Comment by miniwa00** [comment]
upper, lower, inner, outer, overall
인데 이걸로 통일해주세요

**Comment by TaegeunYou** [comment]
넵 main에 머지하시면 ClothesType도 마저 수정할게요

**Comment by sinam7** [comment]
AI 파트에서 사용하는 옷 타입 카테고리 7종으로 맞추어 label 변경 필요.
- 상의 하의 신발 가방 모자 아우터 한벌옷

> ClothesType의 값을 `upper`, `lower`, `shoes`, `bag`, `cap`, `outer`, `overall` 로 수정할 예정
(가방, 신발, 모자 추가, 이너 삭제)

* MaskingType은 아래 내용에 따른 형태로 그대로 유지할 계획

> upper, lower, inner, outer, overall 인데 이걸로 통일해주세요
